<div class="modal-header">
    <button aria-hidden="true" data-dismiss="modal" class="close" type="button">×</button>
    <h3 id="myModalLabel">Kullanıcı Grup Düzeltme Formu</h3>
</div>
<div class="modal-body">
    <div id="div-1" class="accordion-body collapse in body">
        <form class="form-horizontal" id="popUpFormu">
            <input type="hidden" name="id" value="<?php echo $data->id;?>"/>
            <div class="control-group">
                <label for="pass1" class="control-label">Ad Soyad</label>

                <div class="controls with-tooltip">
                    <input type="text" name="name" id="name" class="span3 input-tooltip" data-original-title="Ad" data-placement="bottom" value="<?php echo $data->name;?>"//>
                    <span id="name_error"></span>
                </div>
            </div>
        </form>
    </div>
</div>
<div class="modal-footer">
    <button data-dismiss="modal" class="btn">Kapat</button>
    <button class="btn btn-primary" onclick="neoajax('<?php echo $save_url;?>',getFormValues('popUpFormu'))">Kaydet</button>
</div>
