<div class="modal-header">
    <button aria-hidden="true" data-dismiss="modal" class="close" type="button">×</button>
    <h3 id="myModalLabel">Makale Düzeltme Formu</h3>
</div>
<div class="modal-body">
    <div id="div-1" class="accordion-body collapse in body">
        <form class="form-horizontal" id="popUpFormu">
            <input type="hidden" name="id" value="<?php echo $data->id;?>"/>
            <div class="control-group">
                <label for="name" class="control-label">Seo</label>
                <div class="controls with-tooltip">
                    <input type="text" name="seo" id="seo" class="span6 input-tooltip" data-original-title="Seo" data-placement="bottom" value="<?php echo $data->seo;?>"/>
                    <div class="clearfix"></div>
                    <span id="seo_error" class="error"></span>
                </div>
            </div>
            <div class="control-group">
                <label for="name" class="control-label">Ad</label>
                <div class="controls with-tooltip">
                    <input type="text" name="name" id="name" class="span6 input-tooltip" data-original-title="Ad" data-placement="bottom" value="<?php echo $data->name;?>"/>
                    <div class="clearfix"></div>
                    <span id="name_error" class="error"></span>
                </div>
            </div>
            <div class="control-group">
                <label for="name" class="control-label">Açıklama</label>
                <div class="controls with-tooltip">
                    <textarea name="description" id="description" class="ckeditor"><?php echo $data->description;?></textarea>
                    <span id="description_error" class="error"></span>
                </div>
            </div>
            <div class="control-group">
                <label for="state" class="control-label">Durum</label>

                <div class="controls with-tooltip">
                    <select name="state">
                        <option value=""></option>
                        <option value="1" <?php if ($data->state == 1){ ?> selected="selected" <?php } ?>>Aktif</option>
                        <option value="0" <?php if ($data->state == 0){ ?> selected="selected" <?php } ?>>Pasif</option>
                    </select>
                    <span id="state_error"></span>
                </div>
            </div>
        </form>
    </div>
</div>
<div class="modal-footer">
    <button data-dismiss="modal" class="btn">Kapat</button>
    <button class="btn btn-primary" onclick="neoajax('<?php echo $save_url;?>',getFormValues('popUpFormu'))">Kaydet</button>
</div>
