<?php
$title = 'Edit '.$data->title;
$this->headTitle($title);
?>
<h1><?php echo $this->escapeHtml($title);?></h1>

<form action="" method="post">
    <input type="hidden" name="id" value="<?php echo $data->id;?>"/>
    <table class="table">
        <tr>
            <td>
                <label>Title</label>
            </td>
            <td>
                <input type="text" name="title" id="title" value="<?php echo $data->title;?>"/>
                <?php echo $form->getMessageText('title');?>
            </td>
        </tr>
        <tr>
            <td>
                <label>Artist</label>
            </td>
            <td>
                <input type="text" name="artist" id="artist" value="<?php echo $data->artist;?>"/>
                <?php echo $form->getMessageText('artist');?>
            </td>
        </tr>
        <tr>
            <td colspan="2">
                <input type="submit" value="Kaydet"/>
            </td>
        </tr>
    </table>
</form>