<div class="modal-header">
        <button aria-hidden="true" data-dismiss="modal" class="close" type="button">×</button>
        <h3 id="myModalLabel">Kullanıcı Ekleme Formu</h3>
    </div>
    <div class="modal-body">
        <div id="div-1" class="accordion-body collapse in body">
            <form class="form-horizontal" id="popUpFormu">
                <div class="control-group">
                    <label for="text1" class="control-label">Kullanıcı Adı</label>

                    <div class="controls with-tooltip">
                        <input type="text" name="username" id="username" class="span6 input-tooltip" data-original-title="Kullanıcı Adı" data-placement="bottom"/>
                        <span id="username_error"></span>
                    </div>
                </div>
                <div class="control-group">
                    <label for="pass1" class="control-label">Ad Soyad</label>

                    <div class="controls with-tooltip">
                        <input type="text" name="name" id="name" class="span3 input-tooltip" data-original-title="Ad" data-placement="bottom"/>
                        <input type="text" name="surname" id="surname" class="span3 input-tooltip" data-original-title="Ad" data-placement="bottom"/>
                        <span id="name_error"></span>
                        <span id="surname_error"></span>
                    </div>
                </div>
                <div class="control-group">
                    <label for="text1" class="control-label">Email</label>

                    <div class="controls with-tooltip">
                        <input type="text" name="email" id="email" class="span6 input-tooltip" data-original-title="Email" data-placement="bottom"/>
                        <span id="email_error"></span>
                    </div>
                </div>
            </form>
        </div>
    </div>
    <div class="modal-footer">
        <button data-dismiss="modal" class="btn">Kapat</button>
        <button class="btn btn-primary" onclick="neoajax('<?php echo $save_url;?>',getFormValues('popUpFormu'))">Kaydet</button>
    </div>
