<div class="modal-header">
        <button aria-hidden="true" data-dismiss="modal" class="close" type="button">×</button>
        <h3 id="myModalLabel">Kullanıcı Ekleme Formu</h3>
    </div>
    <div class="modal-body">
        <div id="div-1" class="accordion-body collapse in body">
            <form class="form-horizontal" id="popUpFormu">
                <div class="control-group">
                    <label for="username" class="control-label">Kullanıcı Adı</label>
                    <div class="controls with-tooltip">
                        <input type="text" name="username" id="username" class="span3 input-tooltip" data-original-title="Kullanıcı Adı" data-placement="bottom"/>
                        <div class="clearfix"></div>
                        <span id="username_error" class="error"></span>
                    </div>
                </div>
                <div class="control-group">
                    <label for="name" class="control-label">Ad</label>
                    <div class="controls with-tooltip">
                        <input type="text" name="name" id="name" class="span3 input-tooltip" data-original-title="Ad" data-placement="bottom"/>
                        <div class="clearfix"></div>
                        <span id="name_error" class="error"></span>
                    </div>
                </div>
                <div class="control-group">
                    <label for="surname" class="control-label">Soyad</label>
                    <div class="controls with-tooltip">
                        <input type="text" name="surname" id="surname" class="span3 input-tooltip" data-original-title="Ad" data-placement="bottom"/>
                        <div class="clearfix"></div>
                        <span id="surname_error" class="error"></span>
                    </div>
                </div>
                <div class="control-group">
                    <label for="email" class="control-label">Email</label>
                    <div class="controls with-tooltip">
                        <input type="text" name="email" id="email" class="span3 input-tooltip" data-original-title="Email" data-placement="bottom"/>
                        <div class="clearfix"></div>
                        <span id="email_error" class="error"></span>
                    </div>
                </div>
                <div class="control-group">
                    <label for="state" class="control-label">Durum</label>

                    <div class="controls with-tooltip">
                        <select name="state">
                            <option value=""></option>
                            <option value="1">Aktif</option>
                            <option value="0">Pasif</option>
                        </select>
                        <span id="state_error"></span>
                    </div>
                </div>
            </form>
        </div>
    </div>
    <div class="modal-footer">
        <button data-dismiss="modal" class="btn">Kapat</button>
        <button class="btn btn-primary" onclick="neoajax('<?php echo $save_url;?>',getFormValues('popUpFormu'))">Kaydet</button>
    </div>
