<!--Begin Datatables-->
<div class="row-fluid">
    <div class="span12">
        <div class="box">
            <header>
                <div class="icons"><i class="icon-move"></i></div>
                <h5>Kullanıcılar</h5>
                <button class="btn btn-primary btn-block" onclick="neoajax('<?php echo $this->url('users',array('action'=>'add'));?>',{ })">Yeni Kullanıcı Ekle</button>
            </header>
            <div id="collapse4" class="body">
                <form action="" method="post">
                    <table id="dataTable" class="table table-bordered table-condensed table-hover table-striped sortableTable">
                        <thead>
                            <tr>
                                <th>Kullanıcı Adı</th>
                                <th>Ad</th>
                                <th>Soyad</th>
                                <th>Eposta</th>
                                <th>Durum</th>
                                <th>İşlem</th>
                            </tr>

                        </thead>
                        <tbody>
                        <tr>
                            <th>
                                <div class="controls controls-row">
                                    <input class="span9" placeholder="Kullanıcı Adı" type="text" name="username">
                                </div>
                            </th>
                            <th>
                                <div class="controls controls-row">
                                    <input class="span9" type="text" name="name">
                                </div>
                            </th>
                            <th>
                                <div class="controls controls-row">
                                    <input class="span9" type="text" name="surname">
                                </div>
                            </th>
                            <th>
                                <div class="controls controls-row">
                                    <input class="span9" type="text" name="email">
                                </div>
                            </th>
                            <th>
                                <div class="controls controls-row">
                                    <select name="state">
                                        <option value="-1"></option>
                                        <option value="1">Aktif</option>
                                        <option value="0">Pasif</option>
                                    </select>
                                </div>
                            </th>
                            <th>
                                <input type="submit" value="Ara" class="btn btn-primary">
                            </th>
                        </tr>
                            <?php
                            foreach($paginator AS $row){?>
                                <tr>
                                    <td>
                                        <?php echo $this->escapeHtml($row->username);?>
                                    </td>
                                    <td>
                                        <?php echo $this->escapeHtml($row->name);?>
                                    </td>
                                    <td>
                                        <?php echo $this->escapeHtml($row->surname);?>
                                    </td>
                                    <td>
                                        <?php echo $this->escapeHtml($row->email);?>
                                    </td>
                                    <td>
                                        <?php
                                            if($row->state == 1){
                                                echo "Aktif";
                                            }else{
                                                echo "Pasif";
                                            }
                                        ?>
                                    </td>
                                    <td>
                                        <button class="btn edit" type="button" onclick="neoajax('<?php echo $this->url('users',array('action'=>'edit','id'=>$row->id));?>',{ });"><i class="icon-edit"></i></button>
                                        <button class="btn btn-danger remove"><i class="icon-remove"></i></button>
                                    </td>
                                </tr>
                            <?php
                            }
                            ?>
                        </tbody>
                    </table>
                    <?php
                    echo $this->paginationControl($paginator, 'Sliding', 'paginator-slide', array('order_by' => $order_by, 'order' => $order,'controller'=>'users')
                    );
                    ?>
                </form>
            </div>
        </div>
    </div>
</div>