<?php echo $this->doctype(); ?>
<html>
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
    <title>Login</title>
    <link rel="stylesheet" href="<?php echo $this->basePath();?>/assets/css/bootstrap.min.css">
    <link rel="stylesheet" href="<?php echo $this->basePath();?>/assets/css/login.css">
    <!-- <link rel="stylesheet" href="<?php echo $this->basePath();?>/assets/magic/magic.css">-->
</head>
<body>
<div class="container">

    <?php echo $this->content; ?>

</div> <!-- /container -->

<script src="<?php echo $this->basePath();?>/assets/js/jquery.min.js"></script>
<script type="text/javascript" src="<?php echo $this->basePath();?>/assets/js/vendor/bootstrap.min.js"></script>
<?php echo $this->inlineScript() ?>
<script>
    $('.inline li > a').click(function() {
        var activeForm = $(this).attr('href') + ' > form';
        //console.log(activeForm);
        $(activeForm).addClass('magictime swap');
        //set timer to 1 seconds, after that, unload the magic animation
        setTimeout(function() {
            $(activeForm).removeClass('magictime swap');
        }, 1000);
    });

</script>
</body>
</html>
